server:
  port: 8888
  tomcat:
    max-swallow-size: -1
    #最小线程数
    min-spare-threads: 500
    #最大线程数
    max-threads: 2500
    #最大链接数
    max-connections: 10000
    #最大等待队列长度
    accept-count: 1000
    #请请求体最大长度kb
    #max-http-post-size: 2097152
  servlet:
    context-path: /salary
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

management:
 endpoints:
  web:
   exposure:
    include: metrics,httptrace

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #json 时间戳统一转换
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
  aop:
    proxy-target-class: true
  activiti:
    check-process-definitions: false
    #启用作业执行器
    async-executor-activate: false
    #启用异步执行器
    job-executor-activate: false
  jpa:
    open-in-view: false
  #配置freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    prefer-file-system-access: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 10
        min-idle: 5
        maxActive: 100
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        # 薪资数据库
        master:
          url: jdbc:oracle:thin:@172.16.20.6:1521:RPTDB
          username: oa_g3
          password: OAG3hr1208
          driver-class-name: oracle.jdbc.OracleDriver
        # oa数据库
        oa:
          url: jdbc:oracle:thin:@172.16.20.6:1521:RPTDB
          username: oaprod_new
          password: oaprod
          driver-class-name: oracle.jdbc.OracleDriver

#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:business/**/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: 4
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true

#制造部门codes
manufacturing-dept:
  #组装一期
  dept-a1-assembly-codes: B012000000
  #测试一期
  dept-a1-testing-codes: B293000000
  #组装二期
  dept-d2-assembly-codes: B204000000
  #测试二期
  dept-d2-testing-codes: B206000000
  #组装三期
  dept-a3-assembly-codes: B281000000
  #测试三期
  dept-a3-testing-codes: B285000000
  #圆片级封装部
  packaging-codes: B018000000
  #表面处理中心
  surface-codes: B310000000
  #需要统计的部门名称
  depart-names: A1组装部,A1工艺工程部,A1计划部,A1技术部,A1设备部,A1测试部,A2组装部,A2工艺工程部,A2计划部,A2技术部,A2品质保证部,A2设备部,A2FC,A2测试部,A3组装部,A3工艺工程部,A3其他,A3技术部,A3设备部,A3测试部,CIE,表面处理中心,财务部,崇川厂办公室,动力工程部,工会,技术中心,经营管理办公室,人力资源部,审计部,生产管理部,投资部,物资部,项目办公室,公共事务办公室,销售部,信息技术部,圆片级封装部,质量部,总裁办,CIM制造系统部,Memory,SIP项目部,行政中心总务部,崇川总计,金BP,MEMS元件部,研究院